
TARGET=colorer
all: $(TARGET)

shared_path=../shared/
obj_output=objs

include ../shared/makefile.colorer.gcc

LIBINC = -lm -lstdc++ -fPIC
LIBFLAGS = $(objs) $(FLAGS) -o $(TARGET) $(LIBINC)

include makefile.core

clean:
	$(RM) colorer $(objs)
