
TARGET=colorer.exe
all: $(TARGET)

CYGWIN=-mno-cygwin

shared_path=../shared/
obj_output=objs

include $(shared_path)makefile.colorer.cygwin

LIBINC = -lwininet -lstdc++ -lmingw32
LIBFLAGS = $(objs) $(FLAGS) -o $(TARGET) $(LIBINC) -ggdb
CPPFLAGS_CUSTOM = -DUSE_DL_PREFIX
#CPPFLAGS_CUSTOM =  -ggdb -DCOLORER_FEATURE_LOGLEVEL=COLORER_FEATURE_LOGLEVEL_FULL

include makefile.core

clean:
	$(RM) $(objs)
