
TARGET=libcolorer.so
all: $(TARGET)

shared_path=../shared/
obj_output=../colorer/objs

include ../shared/makefile.colorer.gcc

LIBINC = -lstdc++ -fPIC
LIBFLAGS = $(coreobjects) -shared -o $(TARGET) $(LIBINC)


libcolorer.so: $(coreobjects)
	$(CPP) $(LIBFLAGS)

clean:
	$(RM) $(objs) $(TARGET)
