# Image with prebuilded Xerces-C (uint16_t) for Colorer CI

FROM ghcr.io/colorer/devenv22_base:latest AS build

SHELL ["/bin/bash", "-xeuo", "pipefail", "-c"]

# disable auto-cleaning of the apt cache, so that docker caching works
RUN rm -f /etc/apt/apt.conf.d/docker-clean

# use docker cache for apt packages
RUN --mount=type=cache,target=/var/cache/apt \
<<EOT
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git	        
    rm -rf /var/lib/apt/lists/*
    git config --global http.sslVerify false 
    git clone https://github.com/apache/xerces-c.git
    cd xerces-c
    git checkout v3.2.5
    mkdir build && cd build
    cmake -Dxmlch-type=uint16_t -DCMAKE_INSTALL_PREFIX=/xercesc ..
    cmake --build .
    cmake --install .
EOT


FROM ghcr.io/colorer/devenv22_base:latest

WORKDIR /code
COPY --from=build /xercesc ./xercesc
