# Image for the test build Colorer with gcc/g++ 7.5
# run build from root of project

FROM ghcr.io/colorer/devimage-colorer:gcc7

SHELL ["/bin/bash", "-xeuo", "pipefail", "-c"]

WORKDIR /code

RUN --mount=type=bind,source=.,target=/code/colorer \
<<EOT
    mkdir build
    cmake -S colorer -B build -DCMAKE_BUILD_TYPE=Release -DCOLORER_BUILD_TEST=ON -DCOLORER_USE_VCPKG=OFF \
     -DCOLORER_BUILD_ARCH=x64 -DCOLORER_USE_ICU_STRINGS=OFF -DCOLORER_USE_ZIPINPUTSOURCE=OFF \
     -DCOLORER_BUILD_OLD_COMPILERS=ON -DCOLORER_BUILD_HARD_WARNINGS=OFF
    cmake --build build
    cd ./build/tests/unit
    ./unit_tests
EOT