# Base image for Colorer CI

FROM ubuntu:22.04

SHELL ["/bin/bash", "-xeuo", "pipefail", "-c"]

# disable auto-cleaning of the apt cache, so that docker caching works
RUN rm -f /etc/apt/apt.conf.d/docker-clean

# use docker cache for apt packages
RUN --mount=type=cache,target=/var/cache/apt \
<<EOT
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake gcc g++ make	        
    rm -rf /var/lib/apt/lists/*
EOT