# Image for the test build Colorer with Xerces-C (uint16_t)
# run build from root of project

FROM ghcr.io/colorer/devenv22_xercesc:latest

SHELL ["/bin/bash", "-xeuo", "pipefail", "-c"]

WORKDIR /code

RUN --mount=type=bind,source=.,target=/code/colorer \
<<EOT 
    mkdir build 
    cmake -S colorer -B build -DCOLORER_USE_VCPKG=OFF -DCOLORER_USE_ICU_STRINGS=OFF -DCOLORER_BUILD_TEST=ON \
       -DCOLORER_USE_ZIPINPUTSOURCE=OFF -DCMAKE_PREFIX_PATH=/code/xercesc
    cmake --build build
    ./build/tests/unit/unit_tests
EOT