name: check build

on:
  # workflow_dispatch - manual start build from action menu
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release
  X_VCPKG_NUGET_ID_PREFIX: 'colorer'
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install dependency
        run: sudo apt-get -y install libicu-dev libxerces-c-dev libspdlog-dev libfmt-dev zlib1g-dev libminizip-dev

      - name: Create Build folder
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: >
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCOLORER_BUILD_TEST=ON -DCOLORER_USE_VCPKG=OFF
          -DCOLORER_BUILD_ARCH=x64

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE -j 2

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ./tests/unit/unit_tests

  windows-vc:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64, x86 ]
        include:
          - arch: x64
            triplet: x64-windows-static
          - arch: x86
            triplet: x86-windows-static

    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
          # fetch all for vcpkg versions functionality
          fetch-depth: 0

      - name: Install vcpkg
        run: |
          cd external\vcpkg
          .\bootstrap-vcpkg.bat
          curl -LO https://github.com/colorer/github_tools/releases/download/vcpkg12.09.2021/vcpkg.exe
        # replace vcpkg with patched version (X_VCPKG_NUGET_ID_PREFIX)

      - name: Add C++ build tools to PATH
        uses: ilammy/msvc-dev-cmd@v1.5.0
        with:
          arch: ${{ matrix.arch }}

      - name: Setup NuGet Credentials for vpckg cache
        shell: bash
        run: >
          `$GITHUB_WORKSPACE/external/vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/colorer/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ secrets.PACKAGES_GITHUB_USER }}"
          -password "${{ secrets.PACKAGES_GITHUB_TOKEN }}"

      - name: Create Build forlder
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # add -DVCPKG_INSTALL_OPTIONS="--debug" for debug output
        run: >
          cmake $GITHUB_WORKSPACE -G "Ninja" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVCPKG_BUILD_TYPE=$BUILD_TYPE -DCOLORER_BUILD_TEST=ON
          -DCOLORER_BUILD_ARCH=${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/external/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DVCPKG_OVERLAY_PORTS=$GITHUB_WORKSPACE/external/vcpkg-ports
          -DVCPKG_FEATURE_FLAGS=versions

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./tests/unit/unit_tests.exe
      
