name: Build docker dev images

on:
  # workflow_dispatch - manual start build from action menu
  workflow_dispatch:

jobs:
  dev-images:
    runs-on: ubuntu-22.04

    steps:

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_GITHUB_USER }}
          password: ${{ secrets.PACKAGES_GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          file: ./ci/Dockerfile-base
          push: true
          tags: ghcr.io/colorer/devenv22_base:latest
          cache-from: type=registry,ref=ghcr.io/colorer/devenv22_base:latest
          cache-to: type=inline
