name: "Prebuild vcpkg"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1,3,5'

env:
  BUILD_TYPE: Release
  X_VCPKG_NUGET_ID_PREFIX: 'colorer'
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  windows-vc:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        arch: [ x64, x86 ]
        logger: [ON]
        icu: [ON]
        zip: [ON]
        include:
          - arch: x64
            triplet: x64-win-static-rel
          - arch: x86
            triplet: x86-win-static-rel

    name: windows-${{ matrix.arch }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          bootstrap-vcpkg.bat

      - name: Add C++ build tools to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Setup NuGet Credentials for vcpkg cache
        shell: bash
        run: >
          `vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/colorer/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ secrets.PACKAGES_GITHUB_USER }}"
          -password "${{ secrets.PACKAGES_GITHUB_TOKEN }}"

      - name: Create Build folder
        run: mkdir -p _build

      - name: Configure CMake
        shell: bash
        # add -DVCPKG_INSTALL_OPTIONS="--debug" for debug output
        run: >
          cmake -S . -B _build -G "Ninja"
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCOLORER_BUILD_TEST=OFF
          -DCOLORER_BUILD_ARCH=${{ matrix.arch }}
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -DCOLORER_USE_ICU_STRINGS=${{ matrix.icu }}
          -DCOLORER_USE_ZIPINPUTSOURCE=${{ matrix.zip }}

# dependencies are being built at the configuration stage